framework:
    rate_limiter:
        anonymous_api:
            policy: 'sliding_window'
            limit: 100
            interval: '15 minutes'
        registration_api:
            policy: 'sliding_window'
            limit: 10
            interval: '1 minutes'
        admin_api:
            policy: 'token_bucket'
            limit: 10
            rate: { interval: '1 minute', amount: 5 }
        spraywall_api:
            policy: 'fixed_window'
            limit: 1
            interval: '30 seconds'